<?php

namespace OrangePix\Opxcatalogseo;

class Configurations
{
  const CATEGORY_TITLE = 'OPX_CATALOGSEO_CATEGORY_TITLE';
  const CATEGORY_DESCRIPTION = 'OPX_CATALOGSEO_CATEGORY_DESCRIPTION';
  const PRODUCT_TITLE = 'OPX_CATALOGSEO_PRODUCT_TITLE';
  const PRODUCT_DESCRIPTION = 'OPX_CATALOGSEO_PRODUCT_DESCRIPTION';
  const MANUFACTURER_TITLE = 'OPX_CATALOGSEO_MANUFACTURER_TITLE';
  const MANUFACTURER_DESCRIPTION = 'OPX_CATALOGSEO_MANUFACTURER_DESCRIPTION';
  const H1_OVERRIDE_CATEGORY_NAME = 'OPX_CATALOGSEO_H1_OVERRIDE_CATEGORY_NAME';
}
